// SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later

//! AOT program linker types. These expose no Gambit object representation.

use crate::abi::{GerbilGlobalState, GerbilModuleOrLink};

/// Entry point generated by Gambit for one statically linked module graph.
pub type GerbilProgramLinker =
    unsafe extern "C" fn(*mut GerbilGlobalState) -> *mut GerbilModuleOrLink;

unsafe extern "C" {
    /// Initialize the shared one-shot runtime using a downstream AOT graph.
    ///
    /// # Safety
    ///
    /// The linker must be a live generated Gambit linker for the exact linked
    /// runtime version. Its graph must include the native bridge module. It
    /// must not escape exceptions or initialize another runtime. Call only
    /// through the serialized lifecycle owner; `None` is rejected.
    pub fn gerbil_scheme_rust_runtime_init_program(linker: Option<GerbilProgramLinker>) -> i32;
}
